### ISSUE TITLE
[Feature Request] Documentation: how to build the tank outside of the gui?

### ISSUE THREAD

**Issue by jehon** [jamro/jsbattle#13]
I didn't see it in the documentation, so I don't know if it is a doc missing or a feature request...

Is it possible to inject my own tank from either another location (local folder or a github repository)?

How could I share my tank to run somewhere else (at friends) ?

**Comment by jamro** [comment]
The easiest way is to just copy `*.tank.js` file to `/tanks` folder and update of `/tanks/index.json` file. It is not described in docs but I will add it

**Comment by jamro** [comment]
documented in https://github.com/jamro/jsbattle/blob/master/docs/dev_guide/adding_bundled_tanks.md

**Comment by acklenx** [comment]
This doesn't seem to work.  My new tank doesn't show up in the list if I refresh the page.  And it doesn't even show up if I rebuild.  Has something change? Should I open a bug for this?
