### ISSUE TITLE
Web Worker of 'crawler #2' returned an error: unknown

### ISSUE THREAD

**Issue by maidenone** [jamro/jsbattle#21]
Only "dummy" works, rest of the bots returns error now.
http://jsbattle.jmrlab.com/

**Comment by jamro** [comment]
I could not reproduce it. Maybe there were some connectivity issues. Can you attach any console log? Does the problem still appear?

**Comment by maidenone** [comment]
It works fine now, maybe due to temporary resource limitations on the server side?
