### ISSUE TITLE
Can'r run in docker?

### ISSUE THREAD

**Issue by chris-xstem** [jamro/jsbattle#33]
Tryied different way to dockrize jsbattle server, seems always crash at following place:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/18240977/103881793-e39fdd00-5115-11eb-9f05-8b2e1f1adb69.png">

is there special setting or config we shall be aware of, to make it running in docker?

BTW, we have fixed the --no-sandbox issue.

**Comment by jamro** [comment]
can you attach your Dockerfile and config of JsBattle?

**Comment by chris-xstem** [comment]
Hi, Jamro, 

 

Thanks for the attention.

 

I have it fixed.

 

--

Chris

**Comment by leansoler** [comment]
Would be great @chris-xstem if you can share the solution

**Comment by aprice-dmi** [comment]
Hi @chris-xstem, I have the exact same issue, how do you solve it?

**Comment by franquarato** [comment]
JSBattle uses Puppeteer (Headless Chromium https://github.com/GoogleChrome/puppeteer) to play battles on the server-side.

I had the same problems when I tried to dockerize my application.  But finally following these recommendations I could fix it:
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

But I think will be great if @jamro could add a Dockerfile in the documentation :)
